version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_PATH=essrg
        - TARGET=external
        - NGINX_VERSION=1.25.2-alpine
    container_name: argnginx
    ports:
      - 8080:80
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    
